on:
  push:
    branches:
      - test
      - main
    paths-ignore: 
      - .github/workflows/**

jobs:
  buildpush:
    runs-on: ubuntu-latest
    environment:
        name: A
    steps:
    - uses: actions/checkout@v2

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      run: echo "$MATRIX_CONTEXT"

    - name: change log
      uses: yashanand1910/standard-release-notes@v1.2.1
      id: get_release_notes
      with:
        changelog_path: ./CHANGELOG.md # Optional
        version: ${{ github.ref }} # Required

    - name: Create Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: ${{ steps.get_release_notes.outputs.release_notes }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
