on:
  push:
    branches:
      - test
      - main
    paths-ignore: 
      - .github/workflows/**
  release:
    types:
      - published

jobs:
  buildpush:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Show base branch Name
      run: echo ${{ github.base_ref }}

    - name: Get branch name
      if: github.event_name == 'release'
      shell: bash
      run: echo "branchName=production" >> $GITHUB_ENV
    
    - name: Get branch name
      if: github.event_name != 'release'
      shell: bash
      run: echo "branchName=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
    
    - name: Set env
      run: |
        chmod +x .github/workflows/${{ env.branchName }}.sh 
        ./.github/workflows/${{ env.branchName }}.sh ${{ github.event_name }} ${{ env.branchName }} ${{ github.sha }}

    - name: Set tag(sha)
      if: github.event_name == 'release'
      run: echo "Hellow" 

