on:
  push:
    branches:
      - test
      - main
    paths-ignore: 
      - .github/workflows/**
  release:
    types:
      - published

jobs:
  buildpush:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get branch name
      shell: bash
      run: echo "branchName=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
    
    - name: Set env
      if: env.branchName == 'refs/tags/**'
      run: echo "envname=production" >> $GITHUB_ENV | echo "branchName=${envname}" >> $GITHUB_ENV
    
    - name: Set env(branch Name)
      if: env.branchName != 'refs/tags/**'
      run: echo "envname=${branchName}" >> $GITHUB_ENV | echo "branchName=${envname}" >> $GITHUB_ENV
