on:
  push:
    branches:
      - test
      - main
    paths-ignore: 
      - .github/workflows/**

jobs:
  buildpush:
    runs-on: ubuntu-latest
    env:
        secretA: "{{ "
        secretB: " }}"
        middle: "A"
    steps:
    - uses: actions/checkout@v2

    - name: Show base branch Name
      run: echo ${{ github.base_ref }}

    - name: Get tag version
      shell: bash
      run: echo "tagName=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1
      env:
        secret: $${{ env.secretA }}secrets.TEST_${{ env.middle }}${{ env.secretB }}
      with:
        creds: ${{ env.secret }}
        resource-group: teamMamoruPayTest
        cluster-name: mamoru-pay-test-aks

    - name: Set tag(sha)
      run: echo ${{ env.secret }} 
      env:
        secret: $${{ env.secretA }}secrets.TEST_${{ env.middle }}${{ env.secretB }}
