on:
  push:
    branches:
      - test
      - main
    paths-ignore: 
      - .github/workflows/**

jobs:
  buildpush:
    runs-on: ubuntu-latest
    env:
        secretA: "{{ "
        secretB: " }}"
    steps:
    - uses: actions/checkout@v2

    - name: Show base branch Name
      run: echo ${{ github.base_ref }}

    - name: Get tag version
      shell: bash
      run: echo "tagName=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

    #- name: Set env
      #run: |
        #chmod +x .github/workflows/${{ env.branchName }}.sh 
        #./.github/workflows/${{ env.branchName }}.sh ${{ github.event_name }} $GITHUB_REF ${{ github.sha }}

    - name: Set tag(sha)
      run: echo ${{ env.secret }} 
      env:
        secret: $${{ env.secretA }}secrets.TEST_${{ env.secretB }}
