on:
  push:
    branches:
      - test
      - main
    paths-ignore: 
      - .github/workflows/**

jobs:
  buildpush:
    runs-on: ubuntu-latest
    environment:
        name: A
    steps:
    - uses: actions/checkout@v2

    - name: Show base branch Name
      run: echo ${{ github.base_ref }}

    #- name: Set env
      #run: |
        #chmod +x .github/workflows/main.sh
        #./.github/workflows/main.sh

    - name: create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "AAAAA"
        bodyFile: "BBBBB"
        token: ${{ secrets.GITHUB_TOKEN }}
